version: "3.9"

services:

  postgres:

    image: pgvector/pgvector:pg17

    container_name: stumi_postgres

    restart: always

    environment:
      POSTGRES_USER: stumi
      POSTGRES_PASSWORD: stumi123
      POSTGRES_DB: stumi_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
